const Constants = {
    /*------------GENERAL*-------------*/
    LOADING: 'loading',
    LOADED: 'loaded',
    NODATA: 'nodata',
    LOADED_COUNTRIES: 'loaded_countries',//need to be removed once all app ported into flux
    SELECT_TAB: 'select_tab',
    SELECT_COUNTRY: 'select_country',
    RECEIVED_COUNTRIES_LIST: 'received_countries_list',
    RECEIVED_FARMS_LIST: 'received_farms_list',
    SELECT_FARM: 'select_farm',
    SELECT_TURBINE:'select_turbine',
    RECEIVED_TURBINE_LIST:'received_turbine_list',
    SELECT_TURBINE2:"select_turbine2",
    CHANGE_TEXT: "change_text",
    EMPTY_FORM_FIELDS: 'empty_form_fields',
    RECEIVED_TURBINES_LIST:'received_turbines_list',
    RECEIVED_FARMS_LIST_ALL:'received_farms_list_all',
    GET_FARMS_AND_TURBINES_LIST: 'get_farms_and_turbines_list',
    SET_RIBBON_SUCCESS: 'set_ribbon_success',

    /*---------------------------------*/


    /*------------DASHBOARD--------------*/
    DASHBOARD_LOADING: 'dashboard_loading',
    DASHBOARD_LOADED: 'dashboard_loaded',
    DASHBOARD_NODATA: 'dashboard_nodata',
    DASHBOARD_ALERTSTIME_DATA: 'dashboard_alerts_time',
    DASHBOARD_AVAILABILITY_DATA: 'dashboard_availability_data',
    ALERT_COUNT_DATA: 'alerts_count_data',
    BEST_FARMS_DATA: 'best_farms_data',
    BEST_TURBINES_DATA: 'best_turbine_data',
    WORST_FARMS_DATA: 'worst_farms_data',
    WORST_TURBINES_DATA: 'worst_turbine_data',
    DASHBOARD_PBA_DATA:'dashboard_pba_data',
    /*----------------------------------*/




    /*------------------FLEET-----------------*/
    CHANGE_FLEET_TAB: "change_fleet_tab",
    CHANGE_FLEET_CHARTS: 'change_fleet_charts',
    GET_ALERTS_DATA: 'get_alerts_data',
    GET_FLEET_DATA: 'get_fleet_data',
    SET_DATES: 'set_dates',
    /*---------------------------------------*/

    /*-----------------FARMS------------------*/
    RECEIVED_POWER_WIND: 'received_power_wind',
    RECEIVED_AVAIL_COUNT: 'received_avail_count',
    RECEIVED_ALERTS_COUNT: 'received_alerts_count',
    LOADED_AVAILABILITY: 'loaded_availability_data',
    LOADING_AVAILABILITY: 'loading_availability_data',
    LOADED_PBA: 'loaded_pba_data',
    LOADING_PBA: 'loading_pba_data',
    LOADING_WIND_DATA: 'loading_wind_data_of_farms',
    LOADED_WIND_DATA: 'loaded_wind_data_of_farms',
    RECEIVED_VARIABLES: 'received_variables',
    LOADING_TURBINE_HEAT_MAP_DATA: 'loading_turbine_level_heat_map_data',
    RECEIVED_TURBINE_HEAT_MAP_DATA: 'get_turbine_level_heat_map_data',
    SET_VARIABLE: 'set_variable',
    SET_TURBINE_FARM_COMPARE: 'set_turbine_farm_compare',
    GET_COMPARE_CHART_DATA: 'get_compare_chart_data',
    SET_FARM_TOGGLE : 'set_farm_toggle',
    FARM_FULL_LIFE:'farm_full_life',
    /*----------------------------------------*/


    /*------------------CONTRACT-----------------*/
    CHANGE_TAB_CONTRACT: 'change_tab_contract',
    CANCEL_CONTRACT: 'change_contract',
    SUBMIT_FORM: 'submit_form',
    ADD_ROW_GRID_CONTRACT: 'add_row_grid_contract',
    /*-------------------------------------------*/

    /*------------------EDIT PROFILE-----------------*/
    GET_USER_DETAILS: 'get_user_details',
    RECEIVED_USER_DETAILS: 'received_user_details',
    GET_COUNTRIES: 'get_countries',
    CHANGE_PASSWORD: 'change_password',
    ERROR_COUNT: 'error_count',
    SUBMIT_SETTINGS_FORM: 'submit_settings_form',
    VALIDATE_PASSWORD: 'validate_password',
    CHANGE_TEXT_EDIT_PROFILE: "change_text_edit_profile",
    RESET_STATES_EDIT_PROFILE: 'reset_states_edit_profile',
    /*-----------------------------------------------*/


    /*-----------------ALERTS OVERVIEW---------------*/
    RECEIVED_ALERTS_OVERVIEW_DATA: 'received_alerts_overview_data',
    RECEIVED_ALERTS_SUMMARY_DATA: 'received_alerts_summary_data',
    LOADING_ALERTS_OVERVIEW:'loading_alerts_overview_data',
    LOADING_ALERTS_OVERVIEW_SUMMARY:'loading_alerts_overview_summary',


    /*-----------------SERVICE ASSIST -> ORDERS---------------*/
    GET_ORDERS: 'get_orders',
    UPDATE_ORDERS: 'update_orders',


    /*-----------------MONITOR -> SCADA MONITOR---------------*/
    GET_SCADA_DATA: 'get_scada_data',
    CHUNKIFY_DATA: 'chunkify_data',
    GET_FARMS: 'get_farms',
    CHANGE_FARM_VALUE: 'change_farm_value',
    CHANGE_COUNTRY_VALUE: 'change_country_value',
    ON_COUNT_ZERO: 'on_count_zero',
    GET_COUNTRIES_SCADA: 'get_countries_scada',
    /*------------------TURBINE------------------*/
    SET_VARIABLES_LIST:'set_variables_list',
    SET_VARIABLE_1:'set_variable_1',
    SET_VARIABLE_2:'set_variable_2',
    SET_VARIABLE_3:'set_variable_3',
    SET_VARIABLE_4:'set_variable_4',
    SET_VARIABLE_5:'set_variable_5',
    SET_VARIABLE_6:'set_variable_6',
    SET_PLOT_1:'set_plot_1',
    SET_PLOT_2:'set_plot_2',
    SET_PLOT_3:'set_plot_3',
    SET_PLOT_4:'set_plot_4',
    SET_HISTORY_OF_ALERTS_FOR_TURBINES:'set_history_of_alerts_for_turbines',
    SET_ALERTS_BY_MONTH:'set_alerts_by_month',
    SET_ALERTS_BY_COMPONENT:'set_alerts_by_component',
    SET_TURBINE_AVAILABILITY_DATA:'set_turbine_availability_data',
    SET_TURBINE_PBA_DATA:'set_turbine_pba_data',
    LOADING_INTRA_CHART1:'loading_intra_chart1',
    LOADING_INTRA_CHART2:'loading_intra_chart2',
    LOADING_INTRA_CHART3:'loading_intra_chart3',
    LOADING_INTRA_CHART4:'loading_intra_chart4',
    LOADING_TURBINE_AVAILABILITY:'loading_turbine_availability',
    LOADING_TURBINE_SCADA_DATA: 'loading_turbine_scada_data',
    LOADING_TURBINE_CHART2_SCADA_DATA: 'loading_turbine_chart2_scada_data',
    LOADED_TURBINE_SCADA_DATA: 'loaded_turbine_scada_data',
    LOADED_TURBINE_CHART2_SCADA_DATA: 'loaded_turbine_chart2_scada_data',
    CHANGE_CHART_MODE: 'change_chart_mode',
    LOADING_TURBINE_ALERTS_MONTH:'loading_turbine_alerts_month',
    LOADING_TURBINE_ALERTS_COMP:'loading_turbine_alerts_comp',
    LOADING_TURBINE_AVAILABILITY_PBA:'loading_turbine_availability_pba',
    LOADING_TURBINE_ALERTS_HISTORY:'loading_turbine_alerts_history',
    /*-------------------------------------------*/

    /*----------------CREATE SERVICE ORDER------------------*/
    SEARCH_INPUT_CHANGED: "search_input_changed",
    STATUSCODE_SEARCH_INPUT_CHANGED: 'statuscode_search_input_changed',
    SELECT_STATUS_CODE: 'select_status_code',
    SELECT_RECOMMENDED_OBSERVATIONS: 'select_recommended_observations',
    SHOW_HIDE_POPUP: 'show_hide_popup',
    SELECT_FARM_SERVICE_ORDER: 'select_farm_service_order',
    RECEIVED_TURBINE_LIST_CSR: 'received_turbine_list_csr',
    SELECT_TURBINE_SERVICE_ORDER:'select_turbine_service_order',
    SET_ERROR_MESSAGE_CSO: 'set_error_message_cso',
    SELECT_TURBINE_CSO: 'select_turbine_cso',
    /*------------------------------------------------------*/

    /*----------------WEATHER------------------*/
    GET_COUNTRY_WEATHER: 'select_country_weather',
    GET_FARM_WEATHER: 'select_farms_weather',
    SET_COUNTRY_WEATHER: 'set_country_weather',
    SET_FARM_WEATHER: 'set_farm_weather',
    GET_SHORT_FORECAST_WEATHER: 'get_short_forecast_weather',
    GET_LONG_FORECAST_WEATHER: 'get_long_forecast_weather',
    GET_OVERVIEW_CHART_DATA_WEATHER: 'get_overview_chart_data_weather',
    GET_FARM_SUMMARY_WEATHER: 'get_farm_summary',
    SET_DURATION_1: 'set_duration_1',
    SET_DURATION_2: 'set_duration_2',
    SELECT_CHART: 'select_chart',
    SET_DATE: 'set_date',
    DATA_LOADING: 'data_loading',
    GET_WEATHER_FORECAST_DATA: 'get_weather_forecast_data',
    /*-----------------------------------------*/



    /*------------POWER FORECAST-----------------*/
    LOADED_POWER_FORECAST_DATA: 'loaded_power_forecast_data',
    LOADING_POWER_FORECAST_DATA: 'loading_power_forecast_data',
    LOADED_POWER_FORECAST_DATA_NO_DATA:'loaded_power_forecast_data_no_data',

    /*-------------- CONTRACTS ---------------------*/
    LOADED_CONTRACT_OVERVIEW_DATA: 'loaded_contract_overview_data',
    LOADING_CONTRACT_OVERVIEW_DATA: 'loading_contract_overview_data',
    LOADING_CONTRACT_FIELDS_DATA: 'loading_contract_field_data',
    LOADED_CONTRACT_FIELDS_DATA: 'loaded_contract_field_data',
    SET_CONTRACT: 'set_selected_contract_id',
    SET_CURRENTLY_SHOWING: 'set_currently_showing',
    SET_WIND_PARK: 'set_wind_park',
    SET_CONTRACT_DETAILS:'set_contract_details',
    SET_CONTRACT_YEAR_DETAILS:'set_contract_year_details',
    SET_TURBINE_CONTRACT_DETAILS:'set_turbine_contract_details',
    SET_MODE: 'set_mode',
    ADD_ROW: 'add_rows',
    SET_VALUE: 'set_value',
    SET_CONTRACT_DATA: 'set_contract_data',
    SET_TURBINE_DETAILS_DATA: 'set_turbine_details_data',


    /*-----------------------ALERTS----------------------*/
    ALERTS_SET_ALERT: 'alerts_select_alert',
    ALERTS_LOADED_TURBINES_OF_SAME_FARM: 'alerts_loaded_turbines_of_same_farm',
    ALERTS_LOADED_SCADA_TURBINES_OF_SAME_FARM: 'alerts_loaded_turbines_of_anomaly_report',
    SET_SCADA_TURBINE1: 'set_scada_turbine1',
    SET_SCADA_TURBINE2: 'set_scada_turbine2',
    SET_SCADA_VARIABLES: 'set_scada_variables_list',
    ALERTS_SELECT_TAB: 'alerts_select_tab',
    ALERTS_SELECT_COUNTRY: 'alerts_select_country',
    ALERTS_RECEIVED_COUNTRIES_LIST: 'alerts_received_countries_list',
    ALERTS_RECEIVED_FARMS_LIST: 'alerts_received_farms_list',
    ALERTS_SELECT_FARM: 'alerts_select_farm',
    ALERTS_SELECT_TURBINE:'alerts_select_turbine',
    ALERTS_RECEIVED_TURBINE_LIST:'alerts_received_turbine_list',
    ALERTS_SELECT_TURBINE2:"alerts_select_turbine2",
    ALERTS_SET_VARIABLES_LIST:'alerts_set_variables_list',
    ALERTS_SET_VARIABLE_1:'alerts_set_variable_1',
    ALERTS_SET_VARIABLE_2:'alerts_set_variable_2',
    ALERTS_SET_VARIABLE_3:'alerts_set_variable_3',
    ALERTS_SET_VARIABLE_4:'alerts_set_variable_4',
    ALERTS_SET_PLOT_1:'alerts_set_plot_1',
    ALERTS_SET_PLOT_2:'alerts_set_plot_2',
    ALERTS_SET_PLOT_3:'alerts_set_plot_3',
    ALERTS_SET_PLOT_4:'alerts_set_plot_4',
    ALERTS_SET_HISTORY_OF_ALERTS_FOR_TURBINES:'alerts_set_history_of_alerts_for_turbines',
    ALERTS_SET_ALERTS_BY_MONTH:'alerts_set_alerts_by_month',
    ALERTS_SET_ALERTS_BY_COMPONENT:'alerts_set_alerts_by_component',
    ALERTS_SET_TURBINE_AVAILABILITY_DATA:'alerts_set_turbine_availability_data',
    ALERTS_SET_TURBINE_PBA_DATA:'alerts_set_turbine_pba_data',
    ALERTS_LOADING_INTRA_CHART1:'alerts_loading_intra_chart1',
    ALERTS_LOADING_INTRA_CHART2:'alerts_loading_intra_chart2',
    ALERTS_LOADING_INTRA_CHART3:'alerts_loading_intra_chart3',
    ALERTS_LOADING_INTRA_CHART4:'alerts_loading_intra_chart4',
    ALERTS_LOADING_TURBINE_AVAILABILITY:'alerts_loading_turbine_availability',
    ALERTS_SET_DATES: 'alerts_set_dates',
    ALERTS_CHANGE_CHART_MODE: 'alerts_change_chart_mode',
    ALERTS_SET_VARIABLE_5: 'alerts_set_var_5',
    ALERTS_SET_VARIABLE_6: 'alerts_set_var_6',
    ALERTS_LOADING_TURBINE_SCADA_DATA: 'alerts_loading_turbine_scada_data',
    ALERTS_LOADED_TURBINE_SCADA_DATA: 'alerts_loaded_turbine_scada_data',
    ALERTS_LOADING_TURBINE_CHART2_SCADA_DATA: 'alerts_loading_turbine_chart2_scada_data',
    ALERTS_LOADED_TURBINE_CHART2_SCADA_DATA: 'alerts_loaded_turbine_scada_chart2_data',
    LOADED_ALERTS_SCADA_DATA_VALUES: 'loaded_alerts_scada_data_values',
    LOADING_ALERTS_SCADA_DATA_VALUES: 'loading_alerts_scada_data_values',
    SET_ALERTS_ANOMALY_VARIABLE: 'sst_scada_anomaly_var',
    LOADED_FARM_LEVEL_DATA_FOR_ANOMALY_CHART1: 'loaded_farm_level_data_for_anomaly_chart1',
    LOADING_FARM_LEVEL_DATA_FOR_ANOMALY_CHART1: 'loading_farm_level_data_for_anomaly_chart1',
    LOADED_ALERTS_LIST_DATA: 'loaded_alerts_list_data',
    LOADING_ALERTS_LIST_DATA: 'loading_alerts_list_data',
    LOADED_ALL_TURBINES: 'loaded_all_turbines',
    LOADED_ALERTS_TYPES_LIST: 'loaded_alerts_types_list',
    SET_FINAL_DATE: 'set_alert_initial_date',
    SET_INITIAL_DATE: 'set_alert_finale_date',
    CHANGE_ALERT_TYPE: 'change_alert_type',
    CHANGE_PRIORITY: 'change_alert_priority',
    CHANGE_STATUS: 'change_alerts_status',
    CHANGE_TURBINE: 'change_turbine',
    CLEAR_ALL_DATA: 'clear_all_data',
    SET_PAGE_INDEX: 'set_page_index',
    SET_SCADA_FINAL_DATE: 'set_scada_anomaly_report_set_final_date',
    SET_SCADA_INITIAL_DATE: 'set_scada_anomaly_report_set_initial_date',
    SET_CONTRACT_NUMBER: 'set_contract_number',
    LOADED_DROPDOWN_VALUES: 'loaded_dropdown_values',
    ALERTS_LOADING_TURBINE_AVAILABILITY_PBA:'alerts_loading_turbine_availability_pba',
    ALERTS_LOADING_TURBINE_ALERTS_COMP:'alerts_loading_turbine_availability_pba',
    ALERTS_LOADING_TURBINE_ALERTS_MONTH:'alerts_loading_turbine_alerts_month',
    ALERTS_LOADING_TURBINE_ALERTS_HISTORY:'alerts_loading_turbine_alerts_history',
    UPDATED_CONTRACT: 'updated_contract',
    CHANGE_VALUE: 'change_value',
    SET_SCADA_DATE: 'set_scada_date',
    LOADING_WEATHER_FORECAST_DATA: 'loading_forecast_data',
    LOADING_WEATHER_FORECAST_DATA_FOR_CARDS: 'loading_forecast_data_for_cards',
    LOADED_WEATHER_FORECAST_DATA_FOR_CARDS: 'loaded_forecast_data_for_cards',
    SET_FORECAST_DATE: 'set_forecast_date',
    LOADING_COMPARE_CHART_DATA: 'loading_compare_chart_data',
    SET_DAILY_FORECAST_OFFSET: 'set_daily_forecast_offset',
    SET_HOURLY_FORECAST_OFFSET: 'set_hourly_forecast_offset',
    SET_TURBINE_FARM_COMPARE_NO_DATA: 'set_turbine_farm_compare_no_data',
}
export default Constants;
